#!/usr/bin/env bash
# dns_add_gcloud.sh
# Add TXT record to the Google Cloud DNS
# ver 2025-09-13 
# https://github.com/kshji/getssl_gcloud
#
# Set the TXT DNS record using gcloud command
# 
fulldomain="$1"
token="$2"
all="$*"

PRG="$0"
BINDIR="${PRG%/*}"
[ "$PRG" = "$BINDIR" ] && BINDIR="." # - same dir as program
PRG="${PRG##*/}"

#######################################################################################
dbg()
{


	tmpd="$BINDIR/tmp"
	tmpf="$tmpd/$PRG.log"
	mkdir -p "$tmpd" 2>/dev/null
	chmod 1777 "$tmpd" 2>/dev/null
	

	cnt=0
	# save only last execute info
	date > "$tmpf"
	echo "GCLOUD_PROJECTID:$GCLOUD_PROJECTID"  >> "$tmpf"
	echo "GCLOUD_ZONE:$GCLOUD_ZONE"  >> "$tmpf"
	echo "GCLOUD_ACCOUNT:$GCLOUD_ACCOUNT"  >> "$tmpf"
	echo "GCLOUD_KEYFILE:$GCLOUD_KEYFILE"  >> "$tmpf"
	env >> "$tmpf"
	for var in $all
	do
        	((cnt++))
        	echo "$cnt:<$v>" >> "$tmpf"
	done

}

#######################################################################################
# MAIN
#######################################################################################

[ "$GCLOUD_PROJECTID" = "" ] && echo "GCLOUD_PROJECTID is not set. Unable to set TXT records." && exit 2
[ "$GCLOUD_ZONE" = "" ] && echo "GCLOUD_ZONE is not set. Unable to set TXT records." && exit 2
[ "$GCLOUD_ACCOUNT" = "" ] && echo "GCLOUD_ACCOUNT is not set. Unable to set TXT records." && exit 2
[ "$GCLOUD_KEYFILE" = "" ] && echo "GCLOUD_KEYFILE is not set. Unable to set TXT records." && exit 2
[ ! -f "$GCLOUD_KEYFILE" ] && echo "file not usable:$GCLOUD_KEYFILE" && exit 2

# dbg info to the program tmp dir
# dbg

# activate google cloud account
gcloud auth activate-service-account "$GCLOUD_ACCOUNT" --key-file="$GCLOUD_KEYFILE" --project="$GCLOUD_PROJECTID"
stat=$?
(( stat > 0 )) && echo "gcloud activate account error" && exit 2


# host name
gname="_acme-challenge.$fulldomain."

# start transaction
gcloud dns record-sets transaction start --zone="$GCLOUD_ZONE" --project="$GCLOUD_PROJECTID"
stat=$?
(( stat > 0 )) && echo "gcloud start transaction error" && exit 2

# add TXT
gcloud dns record-sets transaction add  --name="$gname" --ttl=60 --type="TXT" \
	--zone="$GCLOUD_ZONE" --project="$GCLOUD_PROJECTID" "$token"
stat=$?
(( stat > 0 )) && echo "gcloud add error" && exit 2

gcloud dns record-sets transaction execute --zone="$GCLOUD_ZONE" --project="$GCLOUD_PROJECTID"
stat=$?
echo "execute stat:$stat"
(( stat > 0 )) && echo "gcloud transaction execute error" && exit 2

# if not sleep, get error ???
sleep 10
exit 0


